OENIK_PROG3_2019_2_CU5J9O/EventManagement.Web/Models/Guest.cs
namespace EventManagement.Web.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Linq;
    using System.Threading.Tasks;

    /// <summary>
    /// Guest Model for web.
    /// </summary>
    public class Guest
    {
        /// <summary>
        /// Gets or sets ID.
        /// </summary>
        [Display(Name = "Guest ID")]
        [Required]
        public int ID { get; set; }

        /// <summary>
        /// Gets or sets Name.
        /// </summary>
        [Display(Name = "Guest Name")]
        [Required]
        [StringLength(30, MinimumLength = 5)]
        public string Name { get; set; }

        /// <summary>
        /// Gets or sets Contact.
        /// </summary>
        [Display(Name = "Phone Number")]
        [Required]
        [StringLength(10, MinimumLength = 5)]
        public string Contact { get; set; }

        /// <summary>
        /// Gets or sets Email.
        /// </summary>
        [Display(Name = "Guest Email")]
        [Required]
        [StringLength(30, MinimumLength = 5)]
        public string Email { get; set; }

        /// <summary>
        /// Gets or sets City.
        /// </summary>
        [Display(Name = "Guest City")]
        [Required]
        [StringLength(30, MinimumLength = 5)]
        public string City { get; set; }

        /// <summary>
        /// Gets or sets Gender.
        /// </summary>
        [Display(Name = "Guest Gender")]
        [Required]
        [StringLength(30, MinimumLength = 4)]
        public string Gender { get; set; }
    }
}

OENIK_PROG3_2019_2_CU5J9O/EventManagement.Web/Controllers/GuestsController.cs
namespace EventManagement.Web.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using AutoMapper;
    using EventManagement.Logic;
    using EventManagement.Web.Models;
    using Microsoft.AspNetCore.Mvc;

    /// <summary>
    /// This class controll the view for the Guest.
    /// </summary>
    public class GuestsController : Controller
    {
        private IFactoryLogic logic;
        private IMapper mapper;
        private GuestListViewModel vm;

        /// <summary>
        /// Initializes a new instance of the <see cref="GuestsController"/> class.
        /// </summary>
        /// <param name="logic">IFactoryLogic.</param>
        /// <param name="mapper">IMapper.</param>
        public GuestsController(IFactoryLogic logic, IMapper mapper)
        {
            this.logic = logic;
            this.mapper = mapper;

            this.vm = new GuestListViewModel();
            this.vm.EditedGuest = new Models.Guest();

            var guests = logic.GetFrontOfficeLogic().GetAllGuests();
            this.vm.ListOfGuests = mapper.Map<IList<Data.Models.Guest>,
                List<Models.Guest>>(guests);
        }

        /// <summary>
        /// Renders index page.
        /// </summary>
        /// <returns>IActionResult.</returns>
        public IActionResult Index()
        {
            this.ViewData["editAction"] = "AddNew";
            return this.View("GuestIndex", this.vm);
        }

        /// <summary>
        /// Renders details page.
        /// </summary>
        /// <param name="id">guest id.</param>
        /// <returns>IActionResult.</returns>
        public IActionResult Details(int id)
        {
            return this.View("GuestsDetails", this.GetGuestModel(id));
        }

        /// <summary>
        /// Remove the guesta and redirect to index page.
        /// </summary>
        /// <param name="id">Guest Id.</param>
        /// <returns>IActionResult.</returns>
        public IActionResult Remove(int id)
        {
            this.TempData["editResult"] = "Delete Fail";

            if (this.logic.GetAdminstratorLogic().RemoveGuest(id))
            {
                this.TempData["editResult"] = "Delete OK";
            }

            return this.RedirectToAction(nameof(this.Index));
        }

        /// <summary>
        /// This renders edit view in the page.
        /// </summary>
        /// <param name="id">Guest ID.</param>
        /// <returns>IActionResult.</returns>
        public IActionResult Edit(int id)
        {
            this.ViewData["editAction"] = "Edit";
            this.vm.EditedGuest = this.GetGuestModel(id);
            return this.View("GuestIndex", this.vm);
        }

        /// <summary>
        /// Edit the guest or add new guest.
        /// </summary>
        /// <param name="guest">Guest to be edited.</param>
        /// <param name="editAction">String.</param>
        /// <returns>IActionResult.</returns>
        [HttpPost]
        public IActionResult Edit(Models.Guest guest, string editAction)
        {
            if (this.ModelState.IsValid && guest != null)
            {
                this.TempData["editResult"] = "Edit Fail";
                if (editAction == "AddNew")
                {
                    this.logic.GetFrontOfficeLogic().Add(guest.Name, guest.Contact, guest.City, guest.Email, guest.Gender);
                    this.TempData["editResult"] = "Edit Ok";
                }
                else
                {
                    if (this.logic.GetAdminstratorLogic().EditGuest(guest.ID, guest.Name, guest.Email, guest.Contact, guest.Gender, guest.City))
                    {
                        this.TempData["editResult"] = "Edit Ok";
                    }
                }

                return this.RedirectToAction(nameof(this.Index));
            }
            else
            {
                this.ViewData["editAction"] = "Edit";
                this.vm.EditedGuest = guest;
                return this.View("GuestIndex", this.vm);
            }
        }

        private Models.Guest GetGuestModel(int id)
        {
            Data.Models.Guest oneGuest = this.logic.GetFrontOfficeLogic().GetOneGuest(id);
            return this.mapper.Map<Data.Models.Guest, Models.Guest>(oneGuest);
        }
    }
}

OENIK_PROG3_2019_2_CU5J9O/EventManagement.Web/Views/Guests/GuestIndex.cshtml
@model EventManagement.Web.Models.GuestListViewModel

@{
    ViewData["Title"] = "Guest Index";
}

<h2>Guests Index</h2>

<p style="color:red">
    @TempData["editResult"]
</p>

@await Html.PartialAsync("GuestsEdit", Model.EditedGuest)

@await Html.PartialAsync("GuestsList", Model.ListOfGuests)

OENIK_PROG3_2019_2_CU5J9O/EventManagement.Web/Views/Guests/GuestsDetails.cshtml
@model EventManagement.Web.Models.Guest

@{
    ViewData["Title"] = "GuestDetails";
}

<h2>Datasheet of one Guest</h2>

@Html.ActionLink("Back to the list", "Index");

<table border="1">
    <tr>
        <td>@Html.DisplayNameFor(m => m.ID)</td>
        <td>@Html.DisplayFor(m => m.ID)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.Name)</td>
        <td>@Html.DisplayFor(m => m.Name)</td>
    </tr>

    <tr>
        <td>@Html.DisplayNameFor(m => m.Email)</td>
        <td>@Html.DisplayFor(m => m.Email)</td>
    </tr>

    <tr>
        <td>@Html.DisplayNameFor(m => m.Contact)</td>
        <td>@Html.DisplayFor(m => m.Contact)</td>
    </tr>

    <tr>
        <td>@Html.DisplayNameFor(m => m.City)</td>
        <td>@Html.DisplayFor(m => m.City)</td>
    </tr>

    <tr>
        <td>@Html.DisplayNameFor(m => m.Gender)</td>
        <td>@Html.DisplayFor(m => m.Gender)</td>
    </tr>
</table>

OENIK_PROG3_2019_2_CU5J9O/EventManagement.Web/Views/Guests/GuestsEdit.cshtml
@model EventManagement.Web.Models.Guest

<h2>GuestEdit</h2>

@using (Html.BeginForm("Edit", "Guests"))
{
    @Html.ValidationSummary()

    @Html.AntiForgeryToken()

    @Html.HiddenFor(m => m.ID)
    @Html.Hidden("editAction", ViewData["editAction"].ToString());

    <div class="editor-label">@Html.LabelFor(m => m.Name)</div>
    <div class="editor-field">@Html.EditorFor(m => m.Name)</div>

    <div class="editor-label">@Html.LabelFor(m => m.Email)</div>
    <div class="editor-field">@Html.EditorFor(m => m.Email)</div>

    <div class="editor-label">@Html.LabelFor(m => m.Contact)</div>
    <div class="editor-field">@Html.EditorFor(m => m.Contact)</div>

    <div class="editor-label">@Html.LabelFor(m => m.Gender)</div>
    <div class="editor-field">@Html.EditorFor(m => m.Gender)</div>

    <div class="editor-label">@Html.LabelFor(m => m.City)</div>
    <div class="editor-field">@Html.EditorFor(m => m.City)</div>

    <input type="submit" value="SEND" />
}

OENIK_PROG3_2019_2_CU5J9O/EventManagement.Web/Views/Guests/GuestsList.cshtml
@model IEnumerable<EventManagement.Web.Models.Guest>

<h2>GuestList</h2>

@if (Model.Count() == 0)
{
    <p>No data in the database!</p>
}
else
{
    <table border="1">
        <tr>
            <th>@Html.DisplayNameFor(m => m.First().Name)</th>
            <th>@Html.DisplayNameFor(m => m.First().Gender)</th>
            <th>Datasheet</th>
            <th>Delete</th>
            <th>Modify</th>
        </tr>
        @foreach(var item in Model)
        {
            <tr>
                <td>@Html.DisplayFor(m => item.Name)</td>
                <td>@Html.DisplayFor(m => item.Gender)</td>
                <td>@Html.ActionLink("[SHOW]", "Details", new { id = item.ID })</td>
                <td>@Html.ActionLink("[DELETE]", "Remove", new { id = item.ID })</td>
                <td>@Html.ActionLink("[EDIT]", "Edit", new { id = item.ID })</td>
            </tr>
        }
    </table>
}